language: node_js
node_js:
  - 0.12
notifications:
    email: false
services:
  - redis-server

before_install:
- pip install --user codecov
after_success:
- codecov --file coverage/lcov.info --disable search
